# To run the build from the package root:
#    docker buildx build --platform linux/amd64,linux/arm64 -f ./docker-build/Dockerfile.steamos-3.7 -t "breezy-kwin-steamos-3.7" .
#    docker run --rm -t -v ./:/source -v --platform linux/amd64 "breezy-kwin-steamos-3.7:amd64"

FROM --platform=$TARGETPLATFORM ghcr.io/wheaney/holo-base:3.7.20@sha256:1478200c51b8b287e294de6e98a1ab0fb79333503a5cc5681b58dfd209f17851

ARG TARGETPLATFORM
ENV STEAMOS=3.7
RUN echo "SteamOS 3.7 build - target platform: $TARGETPLATFORM"

# CheckSpace can't stat Docker's read-only /etc/hosts and /etc/resolv.conf bind mounts,
# which aborts the transaction; Arch's own container images disable it for this reason
RUN sed -i 's/^[[:space:]]*CheckSpace/#CheckSpace/' /etc/pacman.conf \
 && pacman -Syu --noconfirm --needed \
    ca-certificates \
    base-devel \
    cmake \
    pkgconf \
    git \
    curl \
    wget \
    extra-cmake-modules \
    qt6-base \
    qt6-declarative \
    qt6-quick3d \
    qt6-tools \
    kconfig \
    kconfigwidgets \
    kcoreaddons \
    kglobalaccel \
    ki18n \
    kcmutils \
    kxmlgui \
    kwindowsystem \
    kwin \
    vulkan-headers \
 && pacman -Scc --noconfirm

WORKDIR /source

CMD bin/package_kwin_plugin