# To run the build from the package root:
#    docker buildx build --platform linux/amd64,linux/arm64 -f ./docker-build/Dockerfile.steamos-3.9 -t "breezy-kwin-steamos" .
#    docker run --rm -t -v ./:/source -v --platform linux/amd64 "breezy-kwin-steamos-3.9:amd64"

FROM --platform=$TARGETPLATFORM ghcr.io/wheaney/holo-base:main-3.9@sha256:a9e2c59fb1274cf31d544229134e6bc653f050661dd9b64b05795b964468fcbf

ARG TARGETPLATFORM
ENV STEAMOS=3.9
RUN echo "SteamOS 3.9 build - target platform: $TARGETPLATFORM"

RUN pacman -Sy --noconfirm --needed \
    ca-certificates \
    base-devel \
    cmake \
    pkgconf \
    git \
    curl \
    wget \
    extra-cmake-modules \
    qt6-base \
    qt6-declarative \
    qt6-quick3d \
    qt6-tools \
    kconfig \
    kconfigwidgets \
    kcoreaddons \
    kglobalaccel \
    ki18n \
    kcmutils \
    kxmlgui \
    kwindowsystem \
    kwin \
 && pacman -Scc --noconfirm

WORKDIR /source

CMD bin/package_kwin_plugin