# To run the build from the package root:
#    docker buildx build --platform linux/amd64,linux/arm64 -f ./docker-build/Dockerfile.steamos-3.8 -t "breezy-kwin-steamos" .
#    docker run --rm -t -v ./:/source -v --platform linux/amd64 "breezy-kwin-steamos-3.8:amd64"

FROM --platform=$TARGETPLATFORM ghcr.io/wheaney/holo-base:preview-3.8@sha256:a38cdf4ac0e9022ab55c2078381761b444362cfde63e61d988830b0aafb84850

ARG TARGETPLATFORM
ENV STEAMOS=3.8
RUN echo "SteamOS 3.8 build - target platform: $TARGETPLATFORM"

# CheckSpace can't stat Docker's read-only /etc/hosts and /etc/resolv.conf bind mounts,
# which aborts the transaction; Arch's own container images disable it for this reason
RUN sed -i 's/^[[:space:]]*CheckSpace/#CheckSpace/' /etc/pacman.conf \
 && pacman -Syu --noconfirm --needed \
    ca-certificates \
    base-devel \
    cmake \
    pkgconf \
    git \
    curl \
    wget \
    extra-cmake-modules \
    qt6-base \
    qt6-declarative \
    qt6-quick3d \
    qt6-tools \
    kconfig \
    kconfigwidgets \
    kcoreaddons \
    kglobalaccel \
    ki18n \
    kcmutils \
    kxmlgui \
    kwindowsystem \
    kwin \
    vulkan-headers \
 && pacman -Scc --noconfirm

WORKDIR /source

CMD bin/package_kwin_plugin